version: '3.8'

services:
  server:
    build:
      context: ./server
      target: prod
    ports:
      - "5001:5001"
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=5001
      - FRONTEND_URL=http://localhost:80
      - BACKEND_URL=http://localhost:5001

  client:
    build:
      context: ./client
      target: prod
    ports:
      - "80:80"
    depends_on:
      - server
